# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_entity', models.CharField(max_length=50)),
                ('bid_number', models.CharField(max_length=50)),
                ('bid_title', models.CharField(max_length=50)),
                ('bid_due', models.DateField()),
                ('bid_time', models.TimeField()),
                ('bid_question', models.DateField()),
                ('bid_issue', models.DateField()),
                ('bid_contact_name', models.CharField(max_length=50)),
                ('bid_contact_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=50)),
                ('branch_region', models.CharField(max_length=50)),
                ('branch_contact', models.CharField(max_length=50)),
            ],
        ),
    ]
