# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archived', models.DateTimeField(null=True)),
                ('bid_entity', models.CharField(max_length=50)),
                ('bid_number', models.CharField(max_length=50)),
                ('bid_title', models.CharField(max_length=50)),
                ('bid_due', models.DateField()),
                ('bid_time', models.TimeField()),
                ('bid_question', models.DateField()),
                ('bid_issue', models.DateField()),
                ('bid_contact_name', models.CharField(max_length=50)),
                ('bid_contact_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=50)),
                ('branch_region', models.CharField(max_length=50)),
                ('branch_contact', models.CharField(max_length=50)),
                ('documents', models.ManyToManyField(to='document.Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
