# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='documents',
            field=models.ManyToManyField(null=True, to='document.Document'),
        ),
    ]
