# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='archived',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
